### ISSUE TITLE
"assertion failed: `(39322 == 65535)`" in vdr_dm_data

### ISSUE THREAD

**Issue by rlaphoenix** [quietvoid/dovi_tool#33]
The error occurs here:
https://github.com/quietvoid/dovi_tool/blob/e689da653f564d9b36e3365febad0bac1b02b25b/src/dovi/rpu/vdr_dm_data.rs#L182

Backtrace:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `39322`,
 right: `65535`', src\dovi\rpu\vdr_dm_data.rs:182:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
   2: core::fmt::Arguments::new_v1
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\fmt\mod.rs:338
   3: core::panicking::assert_failed_inner
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:160
   4: core::panicking::assert_failed<u16,u16>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\panicking.rs:117
   5: dovi_tool::dovi::rpu::vdr_dm_data::VdrDmData::validate
             at C:\Users\phoenix\Projects\dovi_tool\src\dovi\rpu\vdr_dm_data.rs:182
   6: dovi_tool::dovi::rpu::rpu_data::DoviRpu::validate
             at C:\Users\phoenix\Projects\dovi_tool\src\dovi\rpu\rpu_data.rs:242
   7: dovi_tool::dovi::io::DoviReader::write_nals
             at C:\Users\phoenix\Projects\dovi_tool\src\dovi\io.rs:262
   8: dovi_tool::dovi::io::DoviReader::read_write_from_io
             at C:\Users\phoenix\Projects\dovi_tool\src\dovi\io.rs:177
   9: dovi_tool::dovi::rpu_extractor::RpuExtractor::extract_rpu_from_el
             at C:\Users\phoenix\Projects\dovi_tool\src\dovi\rpu_extractor.rs:64
  10: dovi_tool::dovi::rpu_extractor::RpuExtractor::process_input
             at C:\Users\phoenix\Projects\dovi_tool\src\dovi\rpu_extractor.rs:56
  11: dovi_tool::dovi::rpu_extractor::RpuExtractor::extract_rpu
             at C:\Users\phoenix\Projects\dovi_tool\src\dovi\rpu_extractor.rs:45
  12: dovi_tool::main
             at C:\Users\phoenix\Projects\dovi_tool\src\main.rs:72
  13: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\ops\function.rs:227
```

This is using dovi_tool compiled at https://github.com/quietvoid/dovi_tool/commit/e689da653f564d9b36e3365febad0bac1b02b25b

The error only occurred at the very end of the extraction process (the progress bar stated `100%`)

**Comment by quietvoid** [comment]
This is sample dependent, but I'm not sure 39322 is valid.

**Comment by rlaphoenix** [comment]
> 
> 
> This is sample dependent, but I'm not sure 39322 is valid (in this case it's only checking profiles over 4)
> Would need the sample to make the validation more specific and fix this.

This content specifically is DRM protected, not sure how I would send you it I'm afraid. Regardless most content on Netflix seems to be failing.

**Comment by quietvoid** [comment]
Since the DM metadata is most likely the same, you can just trim a couple frames of the video.
Or just edit the code, remove the assert and send the RPU values from the `info` subcommand

**Comment by ValZapod** [comment]
> but I'm not sure 39322 is valid

It is. That was eotf on profile 4. Dunno what it is but I suppose PQ too.
